-- Create users table to store user profile data
CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL,
  email TEXT NOT NULL,
  name TEXT NULL,
  picture TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  credits INTEGER NOT NULL DEFAULT 3,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Disable Row Level Security for users table
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

-- Create Interviews table
CREATE TABLE IF NOT EXISTS "Interviews" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  jobposition CHARACTER VARYING NULL,
  jobdescription CHARACTER VARYING NULL,
  duration CHARACTER VARYING NULL,
  type CHARACTER VARYING NULL,
  questionlist JSON NULL,
  useremail CHARACTER VARYING NULL,
  interview_id CHARACTER VARYING NOT NULL,
  resume TEXT NOT NULL,
  CONSTRAINT interviews_pkey PRIMARY KEY (id),
  CONSTRAINT interviews_interview_id_key UNIQUE (interview_id)
) TABLESPACE pg_default;

-- Disable Row Level Security for Interviews table
ALTER TABLE "Interviews" DISABLE ROW LEVEL SECURITY;

-- Add resume column to existing Interviews table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'Interviews' 
        AND column_name = 'resume'
    ) THEN
        ALTER TABLE "Interviews" ADD COLUMN resume TEXT NULL;
    END IF;
END $$;

-- Update existing rows to have empty string for resume
UPDATE "Interviews" SET resume = '' WHERE resume IS NULL;

-- Now make the column NOT NULL
ALTER TABLE "Interviews" ALTER COLUMN resume SET NOT NULL;

-- Create interview_feedback table
CREATE TABLE IF NOT EXISTS interview_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  user_name CHARACTER VARYING NULL,
  user_email CHARACTER VARYING NULL,
  interview_id CHARACTER VARYING NULL,
  feedback JSONB NULL,
  recommended BOOLEAN NULL DEFAULT false,
  CONSTRAINT interview_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT interview_feedback_interview_id_fkey FOREIGN KEY (interview_id) REFERENCES "Interviews" (interview_id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Disable Row Level Security for interview_feedback table
ALTER TABLE interview_feedback DISABLE ROW LEVEL SECURITY;

-- Create storage bucket for resumes
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Public resume access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload resumes" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own resumes" ON storage.objects;

-- Create policy to allow public access to resumes
CREATE POLICY "Public resume access"
ON storage.objects FOR SELECT
USING (bucket_id = 'resumes');

-- Create policy to allow authenticated users to upload resumes
CREATE POLICY "Authenticated users can upload resumes"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'resumes' AND auth.role() = 'authenticated');

-- Create policy to allow users to delete their own resumes
CREATE POLICY "Users can delete own resumes"
ON storage.objects FOR DELETE
USING (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Create function to handle new user creation
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Check if user already exists in users table
  IF EXISTS (SELECT 1 FROM users WHERE id = NEW.id) THEN
    RETURN NEW;
  END IF;

  -- Insert new user with error handling
  BEGIN
    INSERT INTO users (id, email, name, picture, credits)
    VALUES (
      NEW.id,
      NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'given_name', NEW.email),
      COALESCE(NEW.raw_user_meta_data->>'avatar_url', NEW.raw_user_meta_data->>'picture', '/default-avatar.png'),
      3
    );
  EXCEPTION
    WHEN unique_violation THEN
      -- User already exists, ignore
      RETURN NEW;
    WHEN OTHERS THEN
      -- Log error but don't fail the auth
      RAISE WARNING 'Failed to create user record: %', SQLERRM;
      RETURN NEW;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Create trigger to call function on new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- Manual insert for existing user (replace with actual user ID from your screenshot)
-- Uncomment and run this to manually add your existing user
-- INSERT INTO users (id, email, name, picture, credits)
-- VALUES (
--   '2ac77cc1-7b3e-4987-9a1b-e00bcefa552a',
--   'purvprajapati2504@gmail.com',
--   'Purv Prajapati',
--   '/default-avatar.png',
--   3
-- )
-- ON CONFLICT (id) DO UPDATE SET
--   email = EXCLUDED.email,
--   name = EXCLUDED.name,
--   picture = EXCLUDED.picture,
--   credits = EXCLUDED.credits;
